
ALTER TABLE public.uchat_workspaces
  ADD COLUMN IF NOT EXISTS workspace_id TEXT,
  ADD COLUMN IF NOT EXISTS bot_id TEXT,
  ADD COLUMN IF NOT EXISTS max_subscribers INTEGER NOT NULL DEFAULT 1000,
  ADD COLUMN IF NOT EXISTS current_count INTEGER NOT NULL DEFAULT 0;
